define(
    ['ko', 'breeze'],
    function (ko, breeze) {

        var self = this;
        breeze.NamingConvention.camelCase.setAsDefault();
        //self.configFor = function (metadataStore) {
        //    metadataStore.addEntityType({
        //        shortName: "Evento",
        //        namespace: "",
        //        autoGeneratedKeyType: breeze.AutoGeneratedKeyType.Identity,
        //        dataProperties: {
        //            id:          { name: "id", nameOnServer: "Id", dataType: DataType.String, isNullable: false, isPartOfKey: true },
        //            subject:     { name: "subject", nameOnServer: "Subject", dataType: DataType.String, maxLength: 100, isNullable: false },
        //            description: { name: "description", nameOnServer: "Description", dataType: DataType.String, isNullable: false },
        //            start:       { name: "start", nameOnServer: "Start", dataType: DataType.DateTime, isNullable: false },
        //            end:         { name: "end", nameOnServer: "End", dataType: DataType.DateTime, isNullable: false },
        //            color:       { name: "color", nameOnServer: "Color", dataType: DataType.String, isNullable: false }
        //        }
        //    });
        //}

        self.configFor = function (metadataStore) {
            var entityType = new breeze.EntityType({
                shortName: "Evento",
                namespace: "",
                autoGeneratedKeyType: breeze.AutoGeneratedKeyType.Identity
            });
            entityType.addProperty(new breeze.DataProperty({
                name: "id",
                //nameOnServer: "Id",
                dataType: breeze.DataType.String,
                isNullable: false,
                isPartOfKey: true
            }));
            entityType.addProperty(new breeze.DataProperty({
                name: "subject",
                //nameOnServer: "Subject",
                dataType: breeze.DataType.String,
                isNullable: false
            }));
            entityType.addProperty(new breeze.DataProperty({
                name: "description",
                //nameOnServer: "Description",
                dataType: breeze.DataType.String,
                isNullable: false
            }));
            entityType.addProperty(new breeze.DataProperty({
                name: "start",
                //nameOnServer: "Start",
                dataType: breeze.DataType.DateTime,
                isNullable: false
            }));
            entityType.addProperty(new breeze.DataProperty({
                name: "end",
                //nameOnServer: "End",
                dataType: breeze.DataType.DateTime,
                isNullable: false
            }));
            entityType.addProperty(new breeze.DataProperty({
                name: "color",
                //nameOnServer: "Color",
                dataType: breeze.DataType.String,
                isNullable: false
            }));
            metadataStore.addEntityType(entityType);
        }

        return self;
    }
);